In [3]:
import pandas as pd

tech_data_path = 'tech_employee_survey.csv'

In [4]:
df = pd.read_csv(tech_data_path)

df.head()

,Employee_ID,Name,Age,Department,Salary,Years_Experience,Performance_Score,City,Join_Date,Remote_Work
0,1001,John Doe,28,Engineering,75000,3.0,4.0,Dhaka,2020-01-15,Yes
1,1002,ALICE SMITH,32,hr,85000,5.0,5.0,dhaka,15/01/2019,yes
2,1003,Bob Jones,-5,engineering,50000,2.0,8.0,Dhaka,Jan 15 2021,Y
3,1001,John Doe,28,Engineering,75000,3.0,4.0,Dhaka,2020-01-15,Yes
4,1004,Sarah Smith,thirty,HR Department,$120000,7.0,4.0,DHAKA,2021-03-10,True

In [ ]:
df['Join_Date'].head(5)

In [6]:
df.tail()

,Employee_ID,Name,Age,Department,Salary,Years_Experience,Performance_Score,City,Join_Date,Remote_Work
25,1025,Thomas Rodriguez,37,Engineering,50000,10.0,4.0,Sylhet,2018-03-12,yes
26,1005,Mike Wilson,45,Engineering,1000000000,25.0,3.0,Chittagong,2018-07-20,1
27,1026,Nancy Martinez,29,hr,73000,5.0,5.0,Dhaka,2021-04-22,No
28,1027,Christopher Lee,33,Engineering,84000,7.0,0.0,DHAKA,2019-07-08,YES
29,1007,Tom Brown,29,NaN,65000,-2.0,5.0,dhaka,2022-01-01,Maybe

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        30 non-null     int64
 1   Name               30 non-null     object
 2   Age                30 non-null     object
 3   Department         27 non-null     object
 4   Salary             29 non-null     object
 5   Years_Experience   29 non-null     float64
 6   Performance_Score  29 non-null     float64
 7   City               30 non-null     object
 8   Join_Date          30 non-null     object
 9   Remote_Work        30 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 2.5+ KB

In [8]:
df.describe()

       Employee_ID  Years_Experience  Performance_Score
count    30.000000         29.000000          29.000000
mean   1011.633333          8.724138           4.310345
std       7.993460         10.056613           1.983926
min    1001.000000         -2.000000           0.000000
25%    1005.000000          4.000000           4.000000
50%    1010.500000          6.000000           4.000000
75%    1017.750000         10.000000           5.000000
max    1027.000000         50.000000          10.000000

In [11]:
df.duplicated().head(10)

0    False
1    False
2    False
3     True
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [ ]:
print(f"Duplicate rows: df.duplicated().sum()")

np.int64(5)